package lexer

// Lexer performs lexical analysis on Heddle source code, converting raw input
// into a stream of tokens. It supports indentation-based scoping and embedded
// PRQL blocks.
type Lexer struct {
	input        string
	position     int  // current position in input (points to current char)
	readPosition int  // current reading position in input (after current char)
	ch           byte // current char under examination
	line         int  // current line number (1-based)
	column       int  // current column number (0-based)

	indentStack []int     // stack of indentation levels for scope tracking
	pending     []Token   // queue for tokens generated during lookahead (e.g., DEDENTs)
	tabSize     int       // number of spaces a tab represents
	indentStyle rune      // detected indentation style: ' ' for spaces, '\t' for tabs
	lastTokType TokenType // type of the last emitted token for context-sensitive lexing
}

// New initializes a new Lexer with the provided input string.
func New(input string) *Lexer {
	l := &Lexer{
		input:       input,
		line:        1,
		column:      0,
		indentStack: []int{0},
		tabSize:     4, // default tab size if not specified
		indentStyle: 0,
	}
	l.readChar() // initialize first character
	return l
}

// readChar advances the lexer to the next character in the input.
// Sets ch to 0 (ASCII NUL) when the end of input is reached.
func (l *Lexer) readChar() {
	if l.readPosition >= len(l.input) {
		l.ch = 0
	} else {
		l.ch = l.input[l.readPosition]
	}
	l.position = l.readPosition
	l.readPosition++
	l.column++
}

// peekChar returns the next character in the input without advancing the lexer.
func (l *Lexer) peekChar() byte {
	if l.readPosition >= len(l.input) {
		return 0
	}
	return l.input[l.readPosition]
}

// NextToken scans the input for the next available token.
// It prioritizes tokens in the pending queue (generated by indentation logic).
func (l *Lexer) NextToken() Token {
	if len(l.pending) > 0 {
		tok := l.pending[0]
		l.pending = l.pending[1:]
		l.lastTokType = tok.Type
		return tok
	}

	l.skipInlineWhitespace()

	var tok Token

	switch l.ch {
	case '\n', '\r':
		tok = l.handleNewLine()
		l.lastTokType = tok.Type
		return tok
	case '=':
		tok = newToken(ASSIGN, string(l.ch), l.line, l.column)
	case ':':
		tok = newToken(COLON, string(l.ch), l.line, l.column)
	case '{':
		tok = newToken(LBRACE, string(l.ch), l.line, l.column)
	case '}':
		tok = newToken(RBRACE, string(l.ch), l.line, l.column)
	case '(':
		// Check for PRQL block: triggered by '(' following a PIPE or ASSIGN
		if l.lastTokType == PIPE || l.lastTokType == ASSIGN {
			tok.Type = PRQL_BLOCK
			tok.Literal = l.readPRQLBlock()
			tok.Line = l.line
			tok.Column = l.column
			l.lastTokType = tok.Type
			return tok
		}
		tok = newToken(LPAREN, string(l.ch), l.line, l.column)
	case ')':
		tok = newToken(RPAREN, string(l.ch), l.line, l.column)
	case '[':
		tok = newToken(LBRACKET, string(l.ch), l.line, l.column)
	case ']':
		tok = newToken(RBRACKET, string(l.ch), l.line, l.column)
	case '*':
		tok = newToken(ASTERISK, string(l.ch), l.line, l.column)
	case '>':
		tok = newToken(RANGLE, string(l.ch), l.line, l.column)
	case '<':
		tok = newToken(LANGLE, string(l.ch), l.line, l.column)
	case '|':
		tok = newToken(PIPE, string(l.ch), l.line, l.column)
	case '?':
		tok = newToken(QUESTION, string(l.ch), l.line, l.column)
	case ',':
		tok = newToken(COMMA, string(l.ch), l.line, l.column)
	case '.':
		tok = newToken(DOT, string(l.ch), l.line, l.column)
	case '-':
		if l.peekChar() == '>' {
			ch := l.ch
			l.readChar()
			tok = newToken(ARROW, string(ch)+string(l.ch), l.line, l.column-1)
		} else {
			tok = l.readNumber()
			l.lastTokType = tok.Type
			return tok
		}
	case '"':
		tok.Type = STRING_LIT
		tok.Literal = l.readEscapedString()
		tok.Line = l.line
		tok.Column = l.column
		l.lastTokType = tok.Type
		return tok
	case '/':
		if l.peekChar() == '/' {
			l.skipComment()
			return l.NextToken()
		}
		tok = newToken(ILLEGAL, string(l.ch), l.line, l.column)
	case 0:
		// Emit DEDENT tokens for remaining indentation levels at EOF
		if len(l.indentStack) > 1 {
			l.indentStack = l.indentStack[:len(l.indentStack)-1]
			tok = newToken(DEDENT, "", l.line, l.column)
			l.lastTokType = tok.Type
			return tok
		}
		tok.Type = EOF
		tok.Literal = ""
		tok.Line = l.line
		tok.Column = l.column
	default:
		if isLetter(l.ch) {
			tok.Literal = l.readIdentifier()
			tok.Type = LookupIdent(tok.Literal)
			tok.Line = l.line
			tok.Column = l.column
			l.lastTokType = tok.Type
			return tok
		} else if isDigit(l.ch) {
			tok = l.readNumber()
			l.lastTokType = tok.Type
			return tok
		} else {
			tok = newToken(ILLEGAL, string(l.ch), l.line, l.column)
		}
	}

	l.readChar()
	l.lastTokType = tok.Type
	return tok
}

// skipInlineWhitespace consumes horizontal whitespace (spaces and tabs).
func (l *Lexer) skipInlineWhitespace() {
	for l.ch == ' ' || l.ch == '\t' {
		l.readChar()
	}
}

// handleNewLine manages line breaks and indentation-based scoping.
// It generates NEWLINE tokens and manages INDENT/DEDENT transitions.
func (l *Lexer) handleNewLine() Token {
	line := l.line
	col := l.column
	literal := ""

	// consume all consecutive newline characters as a single block
	for l.ch == '\n' || l.ch == '\r' {
		literal += string(l.ch)
		l.readChar()
		l.line++
		l.column = 0
	}

	// capture indentation following the newline
	indentation := ""
	hasSpace := false
	hasTab := false
	for l.ch == ' ' || l.ch == '\t' {
		if l.ch == ' ' {
			hasSpace = true
		} else if l.ch == '\t' {
			hasTab = true
		}
		indentation += string(l.ch)
		l.readChar()
	}

	// validate indentation consistency: mixing tabs and spaces is disallowed
	if hasSpace && hasTab {
		l.pending = append(l.pending, newToken(ILLEGAL, "mixed tabs and spaces in indentation", l.line, 1))
	}

	// enforce a uniform indentation style throughout the file
	if len(indentation) > 0 {
		currentStyle := rune(indentation[0])
		if l.indentStyle == 0 {
			l.indentStyle = currentStyle
		} else if l.indentStyle != currentStyle {
			l.pending = append(l.pending, newToken(ILLEGAL, "conflicting indentation style in file", l.line, 1))
		}
	}

	// skip blank lines or comment-only lines without modifying indentation state
	if l.ch == '\n' || l.ch == '\r' || l.ch == 0 || (l.ch == '/' && l.peekChar() == '/') {
		return l.NextToken()
	}

	// normalize indentation to a numeric level (tabs count as tabSize spaces)
	currentIndent := 0
	for _, char := range indentation {
		if char == ' ' {
			currentIndent++
		} else if char == '\t' {
			currentIndent += l.tabSize
		}
	}

	lastIndent := l.indentStack[len(l.indentStack)-1]

	// compare current indentation against the stack to detect scope changes
	if currentIndent > lastIndent {
		l.indentStack = append(l.indentStack, currentIndent)
		l.pending = append(l.pending, newToken(INDENT, indentation, l.line, 1))
	} else if currentIndent < lastIndent {
		// pop indentation levels until matching an existing outer level
		for currentIndent < lastIndent {
			l.indentStack = l.indentStack[:len(l.indentStack)-1]
			l.pending = append(l.pending, newToken(DEDENT, "", l.line, 1))
			if len(l.indentStack) == 0 {
				break
			}
			lastIndent = l.indentStack[len(l.indentStack)-1]
		}
		// mismatch error if the de-indentation doesn't align with a previous level
		if currentIndent != lastIndent {
			l.pending = append(l.pending, newToken(ILLEGAL, "unindent does not match any outer indentation level", l.line, 1))
		}
	}

	// check if any DEDENT tokens were added to the queue
	hasDedent := false
	for _, t := range l.pending {
		if t.Type == DEDENT {
			hasDedent = true
			break
		}
	}

	nlTok := newToken(NEWLINE, literal, line, col)
	// if dedents exist, they must be emitted BEFORE the newline to maintain block integrity
	if hasDedent {
		l.pending = append(l.pending, nlTok)
		tok := l.pending[0]
		l.pending = l.pending[1:]
		l.lastTokType = tok.Type
		return tok
	}

	l.lastTokType = nlTok.Type
	return nlTok
}

// skipComment consumes characters until the end of the current line.
func (l *Lexer) skipComment() {
	for l.ch != '\n' && l.ch != '\r' && l.ch != 0 {
		l.readChar()
	}
}

// readIdentifier extracts an alphanumeric identifier, including hyphens and underscores.
func (l *Lexer) readIdentifier() string {
	position := l.position
	for isLetter(l.ch) || isDigit(l.ch) || l.ch == '-' {
		l.readChar()
	}
	return l.input[position:l.position]
}

// readNumber extracts a numeric literal, supporting signs and decimal points.
func (l *Lexer) readNumber() Token {
	line := l.line
	col := l.column
	position := l.position
	if l.ch == '-' || l.ch == '+' {
		l.readChar()
	}
	for isDigit(l.ch) {
		l.readChar()
	}
	if l.ch == '.' {
		l.readChar()
		for isDigit(l.ch) {
			l.readChar()
		}
	}
	return Token{Type: NUMBER_LIT, Literal: l.input[position:l.position], Line: line, Column: col}
}

// readEscapedString extracts a double-quoted string literal, handling backslash escapes.
func (l *Lexer) readEscapedString() string {
	l.readChar() // consume opening "
	start := l.position
	for l.ch != '"' && l.ch != 0 {
		if l.ch == '\\' {
			l.readChar() // consume escape character
		}
		l.readChar()
	}
	literal := l.input[start:l.position]
	l.readChar() // consume closing "
	return literal
}

// readPRQLBlock extracts a parenthesized block of PRQL code.
// It maintains parenthesis depth tracking and handles internal string literals.
func (l *Lexer) readPRQLBlock() string {
	start := l.position
	depth := 1
	l.readChar() // consume opening (
	for depth > 0 && l.ch != 0 {
		if l.ch == '(' {
			depth++
		} else if l.ch == ')' {
			depth--
		} else if l.ch == '"' || l.ch == '\'' {
			// skip content within strings to avoid false depth changes
			quote := l.ch
			l.readChar()
			for l.ch != quote && l.ch != 0 {
				if l.ch == '\\' {
					l.readChar()
				}
				l.readChar()
			}
		}
		if depth > 0 {
			l.readChar()
		}
	}
	literal := l.input[start : l.position+1]
	l.readChar() // consume closing )
	return literal
}

// isLetter returns true if the byte is an ASCII letter or underscore.
func isLetter(ch byte) bool {
	return 'a' <= ch && ch <= 'z' || 'A' <= ch && ch <= 'Z' || ch == '_'
}

// isDigit returns true if the byte is an ASCII digit.
func isDigit(ch byte) bool {
	return '0' <= ch && ch <= '9'
}
