// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: sdk/go/proto/locality.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RouteType defines how a resource should be accessed.
type RouteType int32

const (
	RouteType_LOCAL  RouteType = 0 // Access via Unix sockets or shared memory
	RouteType_REMOTE RouteType = 1 // Access via network gRPC/Flight RPC
)

// Enum value maps for RouteType.
var (
	RouteType_name = map[int32]string{
		0: "LOCAL",
		1: "REMOTE",
	}
	RouteType_value = map[string]int32{
		"LOCAL":  0,
		"REMOTE": 1,
	}
)

func (x RouteType) Enum() *RouteType {
	p := new(RouteType)
	*p = x
	return p
}

func (x RouteType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RouteType) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_go_proto_locality_proto_enumTypes[0].Descriptor()
}

func (RouteType) Type() protoreflect.EnumType {
	return &file_sdk_go_proto_locality_proto_enumTypes[0]
}

func (x RouteType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RouteType.Descriptor instead.
func (RouteType) EnumDescriptor() ([]byte, []int) {
	return file_sdk_go_proto_locality_proto_rawDescGZIP(), []int{0}
}

// FlightTicket provides the metadata required for a worker to retrieve a resource.
// This is used as the 'Ticket' in Apache Arrow Flight GetStream or GetFlightInfo.
type FlightTicket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// route_type specifies whether the resource is local or remote.
	RouteType RouteType `protobuf:"varint,1,opt,name=route_type,json=routeType,proto3,enum=heddle.locality.RouteType" json:"route_type,omitempty"`
	// address is the connection string (e.g., unix:///tmp/heddle.sock or grpc://10.0.0.1:50051).
	Address string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	// resource_id is the unique identifier of the allocated in-memory resource.
	ResourceId    string `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlightTicket) Reset() {
	*x = FlightTicket{}
	mi := &file_sdk_go_proto_locality_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlightTicket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlightTicket) ProtoMessage() {}

func (x *FlightTicket) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_go_proto_locality_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlightTicket.ProtoReflect.Descriptor instead.
func (*FlightTicket) Descriptor() ([]byte, []int) {
	return file_sdk_go_proto_locality_proto_rawDescGZIP(), []int{0}
}

func (x *FlightTicket) GetRouteType() RouteType {
	if x != nil {
		return x.RouteType
	}
	return RouteType_LOCAL
}

func (x *FlightTicket) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *FlightTicket) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

var File_sdk_go_proto_locality_proto protoreflect.FileDescriptor

const file_sdk_go_proto_locality_proto_rawDesc = "" +
	"\n" +
	"\x1bsdk/go/proto/locality.proto\x12\x0fheddle.locality\"\x84\x01\n" +
	"\fFlightTicket\x129\n" +
	"\n" +
	"route_type\x18\x01 \x01(\x0e2\x1a.heddle.locality.RouteTypeR\trouteType\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId*\"\n" +
	"\tRouteType\x12\t\n" +
	"\x05LOCAL\x10\x00\x12\n" +
	"\n" +
	"\x06REMOTE\x10\x01B/Z-github.com/galgotech/heddle-lang/sdk/go/protob\x06proto3"

var (
	file_sdk_go_proto_locality_proto_rawDescOnce sync.Once
	file_sdk_go_proto_locality_proto_rawDescData []byte
)

func file_sdk_go_proto_locality_proto_rawDescGZIP() []byte {
	file_sdk_go_proto_locality_proto_rawDescOnce.Do(func() {
		file_sdk_go_proto_locality_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_go_proto_locality_proto_rawDesc), len(file_sdk_go_proto_locality_proto_rawDesc)))
	})
	return file_sdk_go_proto_locality_proto_rawDescData
}

var file_sdk_go_proto_locality_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdk_go_proto_locality_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sdk_go_proto_locality_proto_goTypes = []any{
	(RouteType)(0),       // 0: heddle.locality.RouteType
	(*FlightTicket)(nil), // 1: heddle.locality.FlightTicket
}
var file_sdk_go_proto_locality_proto_depIdxs = []int32{
	0, // 0: heddle.locality.FlightTicket.route_type:type_name -> heddle.locality.RouteType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_sdk_go_proto_locality_proto_init() }
func file_sdk_go_proto_locality_proto_init() {
	if File_sdk_go_proto_locality_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_go_proto_locality_proto_rawDesc), len(file_sdk_go_proto_locality_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_go_proto_locality_proto_goTypes,
		DependencyIndexes: file_sdk_go_proto_locality_proto_depIdxs,
		EnumInfos:         file_sdk_go_proto_locality_proto_enumTypes,
		MessageInfos:      file_sdk_go_proto_locality_proto_msgTypes,
	}.Build()
	File_sdk_go_proto_locality_proto = out.File
	file_sdk_go_proto_locality_proto_goTypes = nil
	file_sdk_go_proto_locality_proto_depIdxs = nil
}
