// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.2
// source: worker.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_SUCCESS        StatusCode = 0
	StatusCode_BUSINESS_ERROR StatusCode = 1
	StatusCode_FATAL_ERROR    StatusCode = 2
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "SUCCESS",
		1: "BUSINESS_ERROR",
		2: "FATAL_ERROR",
	}
	StatusCode_value = map[string]int32{
		"SUCCESS":        0,
		"BUSINESS_ERROR": 1,
		"FATAL_ERROR":    2,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_worker_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_worker_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

type InitResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceName  string                 `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"` // For now, pass config as JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResourceRequest) Reset() {
	*x = InitResourceRequest{}
	mi := &file_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResourceRequest) ProtoMessage() {}

func (x *InitResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResourceRequest.ProtoReflect.Descriptor instead.
func (*InitResourceRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{0}
}

func (x *InitResourceRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *InitResourceRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type InitResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusCode             `protobuf:"varint,1,opt,name=status,proto3,enum=heddle.worker.StatusCode" json:"status,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResourceResponse) Reset() {
	*x = InitResourceResponse{}
	mi := &file_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResourceResponse) ProtoMessage() {}

func (x *InitResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResourceResponse.ProtoReflect.Descriptor instead.
func (*InitResourceResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{1}
}

func (x *InitResourceResponse) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_SUCCESS
}

func (x *InitResourceResponse) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *InitResourceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ExecuteStepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepName      string                 `protobuf:"bytes,1,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`    // Can be empty if the step doesn't require a resource
	ConfigJson    string                 `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`    // Step configuration
	InputTable    []byte                 `protobuf:"bytes,4,opt,name=input_table,json=inputTable,proto3" json:"input_table,omitempty"`    // Placeholder for Arrow buffer
	InputHandle   string                 `protobuf:"bytes,5,opt,name=input_handle,json=inputHandle,proto3" json:"input_handle,omitempty"` // Handle for shared memory (zero-copy)
	OutputHandle  string                 `protobuf:"bytes,6,opt,name=output_handle,json=outputHandle,proto3" json:"output_handle,omitempty"` // Handle for where to write result (zero-copy)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteStepRequest) Reset() {
	*x = ExecuteStepRequest{}
	mi := &file_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteStepRequest) ProtoMessage() {}

func (x *ExecuteStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteStepRequest.ProtoReflect.Descriptor instead.
func (*ExecuteStepRequest) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteStepRequest) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *ExecuteStepRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ExecuteStepRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *ExecuteStepRequest) GetInputTable() []byte {
	if x != nil {
		return x.InputTable
	}
	return nil
}

func (x *ExecuteStepRequest) GetInputHandle() string {
	if x != nil {
		return x.InputHandle
	}
	return ""
}

func (x *ExecuteStepRequest) GetOutputHandle() string {
	if x != nil {
		return x.OutputHandle
	}
	return ""
}

type ExecuteStepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusCode             `protobuf:"varint,1,opt,name=status,proto3,enum=heddle.worker.StatusCode" json:"status,omitempty"`
	OutputTable   []byte                 `protobuf:"bytes,2,opt,name=output_table,json=outputTable,proto3" json:"output_table,omitempty"` // Placeholder for Arrow buffer
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	OutputHandle  string                 `protobuf:"bytes,4,opt,name=output_handle,json=outputHandle,proto3" json:"output_handle,omitempty"` // Handle for shared memory (zero-copy)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteStepResponse) Reset() {
	*x = ExecuteStepResponse{}
	mi := &file_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteStepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteStepResponse) ProtoMessage() {}

func (x *ExecuteStepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteStepResponse.ProtoReflect.Descriptor instead.
func (*ExecuteStepResponse) Descriptor() ([]byte, []int) {
	return file_worker_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteStepResponse) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_SUCCESS
}

func (x *ExecuteStepResponse) GetOutputTable() []byte {
	if x != nil {
		return x.OutputTable
	}
	return nil
}

func (x *ExecuteStepResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ExecuteStepResponse) GetOutputHandle() string {
	if x != nil {
		return x.OutputHandle
	}
	return ""
}

var File_worker_proto protoreflect.FileDescriptor

const file_worker_proto_rawDesc = "" +
	"\n" +
	"\fworker.proto\x12\rheddle.worker\"[\n" +
	"\x13InitResourceRequest\x12#\n" +
	"\rresource_name\x18\x01 \x01(\tR\fresourceName\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\tR\n" +
	"configJson\"\x8f\x01\n" +
	"\x14InitResourceResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.heddle.worker.StatusCodeR\x06status\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\x94\x01\n" +
	"\x12ExecuteStepRequest\x12\x1b\n" +
	"\tstep_name\x18\x01 \x01(\tR\bstepName\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\tR\n" +
	"configJson\x12\x1f\n" +
	"\vinput_table\x18\x04 \x01(\fR\n" +
	"inputTable\"\x90\x01\n" +
	"\x13ExecuteStepResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.heddle.worker.StatusCodeR\x06status\x12!\n" +
	"\foutput_table\x18\x02 \x01(\fR\voutputTable\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage*>\n" +
	"\n" +
	"StatusCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x12\n" +
	"\x0eBUSINESS_ERROR\x10\x01\x12\x0f\n" +
	"\vFATAL_ERROR\x10\x022\xc2\x01\n" +
	"\rPluginService\x12Y\n" +
	"\fInitResource\x12\".heddle.worker.InitResourceRequest\x1a#.heddle.worker.InitResourceResponse\"\x00\x12V\n" +
	"\vExecuteStep\x12!.heddle.worker.ExecuteStepRequest\x1a\".heddle.worker.ExecuteStepResponse\"\x00B/Z-github.com/galgotech/heddle-lang/sdk/go/protob\x06proto3"

var (
	file_worker_proto_rawDescOnce sync.Once
	file_worker_proto_rawDescData []byte
)

func file_worker_proto_rawDescGZIP() []byte {
	file_worker_proto_rawDescOnce.Do(func() {
		file_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)))
	})
	return file_worker_proto_rawDescData
}

var file_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_worker_proto_goTypes = []any{
	(StatusCode)(0),              // 0: heddle.worker.StatusCode
	(*InitResourceRequest)(nil),  // 1: heddle.worker.InitResourceRequest
	(*InitResourceResponse)(nil), // 2: heddle.worker.InitResourceResponse
	(*ExecuteStepRequest)(nil),   // 3: heddle.worker.ExecuteStepRequest
	(*ExecuteStepResponse)(nil),  // 4: heddle.worker.ExecuteStepResponse
}
var file_worker_proto_depIdxs = []int32{
	0, // 0: heddle.worker.InitResourceResponse.status:type_name -> heddle.worker.StatusCode
	0, // 1: heddle.worker.ExecuteStepResponse.status:type_name -> heddle.worker.StatusCode
	1, // 2: heddle.worker.PluginService.InitResource:input_type -> heddle.worker.InitResourceRequest
	3, // 3: heddle.worker.PluginService.ExecuteStep:input_type -> heddle.worker.ExecuteStepRequest
	2, // 4: heddle.worker.PluginService.InitResource:output_type -> heddle.worker.InitResourceResponse
	4, // 5: heddle.worker.PluginService.ExecuteStep:output_type -> heddle.worker.ExecuteStepResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_worker_proto_init() }
func file_worker_proto_init() {
	if File_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_proto_rawDesc), len(file_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_proto_goTypes,
		DependencyIndexes: file_worker_proto_depIdxs,
		EnumInfos:         file_worker_proto_enumTypes,
		MessageInfos:      file_worker_proto_msgTypes,
	}.Build()
	File_worker_proto = out.File
	file_worker_proto_goTypes = nil
	file_worker_proto_depIdxs = nil
}
