// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: sdk/go/proto/worker.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusCode int32

const (
	StatusCode_SUCCESS        StatusCode = 0
	StatusCode_BUSINESS_ERROR StatusCode = 1
	StatusCode_FATAL_ERROR    StatusCode = 2
)

// Enum value maps for StatusCode.
var (
	StatusCode_name = map[int32]string{
		0: "SUCCESS",
		1: "BUSINESS_ERROR",
		2: "FATAL_ERROR",
	}
	StatusCode_value = map[string]int32{
		"SUCCESS":        0,
		"BUSINESS_ERROR": 1,
		"FATAL_ERROR":    2,
	}
)

func (x StatusCode) Enum() *StatusCode {
	p := new(StatusCode)
	*p = x
	return p
}

func (x StatusCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StatusCode) Descriptor() protoreflect.EnumDescriptor {
	return file_sdk_go_proto_worker_proto_enumTypes[0].Descriptor()
}

func (StatusCode) Type() protoreflect.EnumType {
	return &file_sdk_go_proto_worker_proto_enumTypes[0]
}

func (x StatusCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StatusCode.Descriptor instead.
func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return file_sdk_go_proto_worker_proto_rawDescGZIP(), []int{0}
}

type InitResourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ResourceName  string                 `protobuf:"bytes,1,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"` // For now, pass config as JSON
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResourceRequest) Reset() {
	*x = InitResourceRequest{}
	mi := &file_sdk_go_proto_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResourceRequest) ProtoMessage() {}

func (x *InitResourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_go_proto_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResourceRequest.ProtoReflect.Descriptor instead.
func (*InitResourceRequest) Descriptor() ([]byte, []int) {
	return file_sdk_go_proto_worker_proto_rawDescGZIP(), []int{0}
}

func (x *InitResourceRequest) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

func (x *InitResourceRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type InitResourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusCode             `protobuf:"varint,1,opt,name=status,proto3,enum=heddle.worker.StatusCode" json:"status,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResourceResponse) Reset() {
	*x = InitResourceResponse{}
	mi := &file_sdk_go_proto_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResourceResponse) ProtoMessage() {}

func (x *InitResourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_go_proto_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResourceResponse.ProtoReflect.Descriptor instead.
func (*InitResourceResponse) Descriptor() ([]byte, []int) {
	return file_sdk_go_proto_worker_proto_rawDescGZIP(), []int{1}
}

func (x *InitResourceResponse) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_SUCCESS
}

func (x *InitResourceResponse) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *InitResourceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ExecuteStepRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepName      string                 `protobuf:"bytes,1,opt,name=step_name,json=stepName,proto3" json:"step_name,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`       // Can be empty if the step doesn't require a resource
	ConfigJson    string                 `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`       // Step configuration
	InputTable    []byte                 `protobuf:"bytes,4,opt,name=input_table,json=inputTable,proto3" json:"input_table,omitempty"`       // Placeholder for Arrow buffer
	InputHandle   string                 `protobuf:"bytes,5,opt,name=input_handle,json=inputHandle,proto3" json:"input_handle,omitempty"`    // Handle for shared memory (zero-copy)
	OutputHandle  string                 `protobuf:"bytes,6,opt,name=output_handle,json=outputHandle,proto3" json:"output_handle,omitempty"` // Handle for where to write result (zero-copy)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteStepRequest) Reset() {
	*x = ExecuteStepRequest{}
	mi := &file_sdk_go_proto_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteStepRequest) ProtoMessage() {}

func (x *ExecuteStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_go_proto_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteStepRequest.ProtoReflect.Descriptor instead.
func (*ExecuteStepRequest) Descriptor() ([]byte, []int) {
	return file_sdk_go_proto_worker_proto_rawDescGZIP(), []int{2}
}

func (x *ExecuteStepRequest) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *ExecuteStepRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *ExecuteStepRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *ExecuteStepRequest) GetInputTable() []byte {
	if x != nil {
		return x.InputTable
	}
	return nil
}

func (x *ExecuteStepRequest) GetInputHandle() string {
	if x != nil {
		return x.InputHandle
	}
	return ""
}

func (x *ExecuteStepRequest) GetOutputHandle() string {
	if x != nil {
		return x.OutputHandle
	}
	return ""
}

type ExecuteStepResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        StatusCode             `protobuf:"varint,1,opt,name=status,proto3,enum=heddle.worker.StatusCode" json:"status,omitempty"`
	OutputTable   []byte                 `protobuf:"bytes,2,opt,name=output_table,json=outputTable,proto3" json:"output_table,omitempty"` // Placeholder for Arrow buffer
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	OutputHandle  string                 `protobuf:"bytes,4,opt,name=output_handle,json=outputHandle,proto3" json:"output_handle,omitempty"` // Handle for shared memory (zero-copy)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteStepResponse) Reset() {
	*x = ExecuteStepResponse{}
	mi := &file_sdk_go_proto_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteStepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteStepResponse) ProtoMessage() {}

func (x *ExecuteStepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_go_proto_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteStepResponse.ProtoReflect.Descriptor instead.
func (*ExecuteStepResponse) Descriptor() ([]byte, []int) {
	return file_sdk_go_proto_worker_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteStepResponse) GetStatus() StatusCode {
	if x != nil {
		return x.Status
	}
	return StatusCode_SUCCESS
}

func (x *ExecuteStepResponse) GetOutputTable() []byte {
	if x != nil {
		return x.OutputTable
	}
	return nil
}

func (x *ExecuteStepResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ExecuteStepResponse) GetOutputHandle() string {
	if x != nil {
		return x.OutputHandle
	}
	return ""
}

type StepMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ConfigJsonSchema string                 `protobuf:"bytes,2,opt,name=config_json_schema,json=configJsonSchema,proto3" json:"config_json_schema,omitempty"`
	RequiresResource bool                   `protobuf:"varint,3,opt,name=requires_resource,json=requiresResource,proto3" json:"requires_resource,omitempty"`
	ResourceName     string                 `protobuf:"bytes,4,opt,name=resource_name,json=resourceName,proto3" json:"resource_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StepMetadata) Reset() {
	*x = StepMetadata{}
	mi := &file_sdk_go_proto_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepMetadata) ProtoMessage() {}

func (x *StepMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_go_proto_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepMetadata.ProtoReflect.Descriptor instead.
func (*StepMetadata) Descriptor() ([]byte, []int) {
	return file_sdk_go_proto_worker_proto_rawDescGZIP(), []int{4}
}

func (x *StepMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StepMetadata) GetConfigJsonSchema() string {
	if x != nil {
		return x.ConfigJsonSchema
	}
	return ""
}

func (x *StepMetadata) GetRequiresResource() bool {
	if x != nil {
		return x.RequiresResource
	}
	return false
}

func (x *StepMetadata) GetResourceName() string {
	if x != nil {
		return x.ResourceName
	}
	return ""
}

type ResourceMetadata struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ConfigJsonSchema string                 `protobuf:"bytes,2,opt,name=config_json_schema,json=configJsonSchema,proto3" json:"config_json_schema,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ResourceMetadata) Reset() {
	*x = ResourceMetadata{}
	mi := &file_sdk_go_proto_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceMetadata) ProtoMessage() {}

func (x *ResourceMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_go_proto_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceMetadata.ProtoReflect.Descriptor instead.
func (*ResourceMetadata) Descriptor() ([]byte, []int) {
	return file_sdk_go_proto_worker_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ResourceMetadata) GetConfigJsonSchema() string {
	if x != nil {
		return x.ConfigJsonSchema
	}
	return ""
}

type DescribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steps         []*StepMetadata        `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	Resources     []*ResourceMetadata    `protobuf:"bytes,2,rep,name=resources,proto3" json:"resources,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeResponse) Reset() {
	*x = DescribeResponse{}
	mi := &file_sdk_go_proto_worker_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeResponse) ProtoMessage() {}

func (x *DescribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sdk_go_proto_worker_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeResponse.ProtoReflect.Descriptor instead.
func (*DescribeResponse) Descriptor() ([]byte, []int) {
	return file_sdk_go_proto_worker_proto_rawDescGZIP(), []int{6}
}

func (x *DescribeResponse) GetSteps() []*StepMetadata {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *DescribeResponse) GetResources() []*ResourceMetadata {
	if x != nil {
		return x.Resources
	}
	return nil
}

var File_sdk_go_proto_worker_proto protoreflect.FileDescriptor

const file_sdk_go_proto_worker_proto_rawDesc = "" +
	"\n" +
	"\x19sdk/go/proto/worker.proto\x12\rheddle.worker\x1a\x1bgoogle/protobuf/empty.proto\"[\n" +
	"\x13InitResourceRequest\x12#\n" +
	"\rresource_name\x18\x01 \x01(\tR\fresourceName\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\tR\n" +
	"configJson\"\x8f\x01\n" +
	"\x14InitResourceResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.heddle.worker.StatusCodeR\x06status\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xdc\x01\n" +
	"\x12ExecuteStepRequest\x12\x1b\n" +
	"\tstep_name\x18\x01 \x01(\tR\bstepName\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\tR\n" +
	"configJson\x12\x1f\n" +
	"\vinput_table\x18\x04 \x01(\fR\n" +
	"inputTable\x12!\n" +
	"\finput_handle\x18\x05 \x01(\tR\vinputHandle\x12#\n" +
	"\routput_handle\x18\x06 \x01(\tR\foutputHandle\"\xb5\x01\n" +
	"\x13ExecuteStepResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.heddle.worker.StatusCodeR\x06status\x12!\n" +
	"\foutput_table\x18\x02 \x01(\fR\voutputTable\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12#\n" +
	"\routput_handle\x18\x04 \x01(\tR\foutputHandle\"\xa2\x01\n" +
	"\fStepMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x12config_json_schema\x18\x02 \x01(\tR\x10configJsonSchema\x12+\n" +
	"\x11requires_resource\x18\x03 \x01(\bR\x10requiresResource\x12#\n" +
	"\rresource_name\x18\x04 \x01(\tR\fresourceName\"T\n" +
	"\x10ResourceMetadata\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x12config_json_schema\x18\x02 \x01(\tR\x10configJsonSchema\"\x84\x01\n" +
	"\x10DescribeResponse\x121\n" +
	"\x05steps\x18\x01 \x03(\v2\x1b.heddle.worker.StepMetadataR\x05steps\x12=\n" +
	"\tresources\x18\x02 \x03(\v2\x1f.heddle.worker.ResourceMetadataR\tresources*>\n" +
	"\n" +
	"StatusCode\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\x12\n" +
	"\x0eBUSINESS_ERROR\x10\x01\x12\x0f\n" +
	"\vFATAL_ERROR\x10\x02B/Z-github.com/galgotech/heddle-lang/sdk/go/protob\x06proto3"

var (
	file_sdk_go_proto_worker_proto_rawDescOnce sync.Once
	file_sdk_go_proto_worker_proto_rawDescData []byte
)

func file_sdk_go_proto_worker_proto_rawDescGZIP() []byte {
	file_sdk_go_proto_worker_proto_rawDescOnce.Do(func() {
		file_sdk_go_proto_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sdk_go_proto_worker_proto_rawDesc), len(file_sdk_go_proto_worker_proto_rawDesc)))
	})
	return file_sdk_go_proto_worker_proto_rawDescData
}

var file_sdk_go_proto_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sdk_go_proto_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_sdk_go_proto_worker_proto_goTypes = []any{
	(StatusCode)(0),              // 0: heddle.worker.StatusCode
	(*InitResourceRequest)(nil),  // 1: heddle.worker.InitResourceRequest
	(*InitResourceResponse)(nil), // 2: heddle.worker.InitResourceResponse
	(*ExecuteStepRequest)(nil),   // 3: heddle.worker.ExecuteStepRequest
	(*ExecuteStepResponse)(nil),  // 4: heddle.worker.ExecuteStepResponse
	(*StepMetadata)(nil),         // 5: heddle.worker.StepMetadata
	(*ResourceMetadata)(nil),     // 6: heddle.worker.ResourceMetadata
	(*DescribeResponse)(nil),     // 7: heddle.worker.DescribeResponse
}
var file_sdk_go_proto_worker_proto_depIdxs = []int32{
	0, // 0: heddle.worker.InitResourceResponse.status:type_name -> heddle.worker.StatusCode
	0, // 1: heddle.worker.ExecuteStepResponse.status:type_name -> heddle.worker.StatusCode
	5, // 2: heddle.worker.DescribeResponse.steps:type_name -> heddle.worker.StepMetadata
	6, // 3: heddle.worker.DescribeResponse.resources:type_name -> heddle.worker.ResourceMetadata
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_sdk_go_proto_worker_proto_init() }
func file_sdk_go_proto_worker_proto_init() {
	if File_sdk_go_proto_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sdk_go_proto_worker_proto_rawDesc), len(file_sdk_go_proto_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sdk_go_proto_worker_proto_goTypes,
		DependencyIndexes: file_sdk_go_proto_worker_proto_depIdxs,
		EnumInfos:         file_sdk_go_proto_worker_proto_enumTypes,
		MessageInfos:      file_sdk_go_proto_worker_proto_msgTypes,
	}.Build()
	File_sdk_go_proto_worker_proto = out.File
	file_sdk_go_proto_worker_proto_goTypes = nil
	file_sdk_go_proto_worker_proto_depIdxs = nil
}
