# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: heddle/proto/worker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'heddle/proto/worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19heddle/proto/worker.proto\x12\rheddle.worker\"A\n\x13InitResourceRequest\x12\x15\n\rresource_name\x18\x01 \x01(\t\x12\x13\n\x0b\x63onfig_json\x18\x02 \x01(\t\"m\n\x14InitResourceResponse\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.heddle.worker.StatusCode\x12\x13\n\x0bresource_id\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\"f\n\x12\x45xecuteStepRequest\x12\x11\n\tstep_name\x18\x01 \x01(\t\x12\x13\n\x0bresource_id\x18\x02 \x01(\t\x12\x13\n\x0b\x63onfig_json\x18\x03 \x01(\t\x12\x13\n\x0binput_table\x18\x04 \x01(\x0c\"m\n\x13\x45xecuteStepResponse\x12)\n\x06status\x18\x01 \x01(\x0e\x32\x19.heddle.worker.StatusCode\x12\x14\n\x0coutput_table\x18\x02 \x01(\x0c\x12\x15\n\rerror_message\x18\x03 \x01(\t*>\n\nStatusCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x12\n\x0e\x42USINESS_ERROR\x10\x01\x12\x0f\n\x0b\x46\x41TAL_ERROR\x10\x02\x32\xc2\x01\n\rPluginService\x12Y\n\x0cInitResource\x12\".heddle.worker.InitResourceRequest\x1a#.heddle.worker.InitResourceResponse\"\x00\x12V\n\x0b\x45xecuteStep\x12!.heddle.worker.ExecuteStepRequest\x1a\".heddle.worker.ExecuteStepResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'heddle.proto.worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STATUSCODE']._serialized_start=437
  _globals['_STATUSCODE']._serialized_end=499
  _globals['_INITRESOURCEREQUEST']._serialized_start=44
  _globals['_INITRESOURCEREQUEST']._serialized_end=109
  _globals['_INITRESOURCERESPONSE']._serialized_start=111
  _globals['_INITRESOURCERESPONSE']._serialized_end=220
  _globals['_EXECUTESTEPREQUEST']._serialized_start=222
  _globals['_EXECUTESTEPREQUEST']._serialized_end=324
  _globals['_EXECUTESTEPRESPONSE']._serialized_start=326
  _globals['_EXECUTESTEPRESPONSE']._serialized_end=435
  _globals['_PLUGINSERVICE']._serialized_start=502
  _globals['_PLUGINSERVICE']._serialized_end=696
# @@protoc_insertion_point(module_scope)
