# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from heddle.proto import worker_pb2 as heddle_dot_proto_dot_worker__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in heddle/proto/worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitResource = channel.unary_unary(
                '/heddle.worker.PluginService/InitResource',
                request_serializer=heddle_dot_proto_dot_worker__pb2.InitResourceRequest.SerializeToString,
                response_deserializer=heddle_dot_proto_dot_worker__pb2.InitResourceResponse.FromString,
                _registered_method=True)
        self.ExecuteStep = channel.unary_unary(
                '/heddle.worker.PluginService/ExecuteStep',
                request_serializer=heddle_dot_proto_dot_worker__pb2.ExecuteStepRequest.SerializeToString,
                response_deserializer=heddle_dot_proto_dot_worker__pb2.ExecuteStepResponse.FromString,
                _registered_method=True)


class PluginServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteStep(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitResource': grpc.unary_unary_rpc_method_handler(
                    servicer.InitResource,
                    request_deserializer=heddle_dot_proto_dot_worker__pb2.InitResourceRequest.FromString,
                    response_serializer=heddle_dot_proto_dot_worker__pb2.InitResourceResponse.SerializeToString,
            ),
            'ExecuteStep': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteStep,
                    request_deserializer=heddle_dot_proto_dot_worker__pb2.ExecuteStepRequest.FromString,
                    response_serializer=heddle_dot_proto_dot_worker__pb2.ExecuteStepResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'heddle.worker.PluginService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('heddle.worker.PluginService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heddle.worker.PluginService/InitResource',
            heddle_dot_proto_dot_worker__pb2.InitResourceRequest.SerializeToString,
            heddle_dot_proto_dot_worker__pb2.InitResourceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteStep(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/heddle.worker.PluginService/ExecuteStep',
            heddle_dot_proto_dot_worker__pb2.ExecuteStepRequest.SerializeToString,
            heddle_dot_proto_dot_worker__pb2.ExecuteStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
